### ISSUE TITLE
create for 1.12.2

### ISSUE THREAD

**Issue by WhiteTan2** [Coderx-Gamer/shulker-dupe#12]
Good
Can you create for 1.12.2 ?

**Comment by N3rmis** [comment]
i asked him to but he ignored idk

**Comment by LoganDark** [comment]
https://howoldisminecraft1122.today/

**Comment by Coderx-Gamer** [comment]
I don't really know how 1.12.2 code and forge works, if someone is willing to create one I will add it to releases.
