### ISSUE TITLE
FPS drop issue

### ISSUE THREAD

**Issue by Samozd** [Coderx-Gamer/shulker-dupe#18]
I really don't know much about how this works, but FPS starts dropping whenever I go in the shulker box gui.
I think this is because a new button is added every frame? Not sure about that though since I don't know how this functions.
You can observe this by pressing Shift+F3 and opening a shulker GUI, gameRenderer in the pie chart will become increasingly larger.
I believe the code causing this is in [here](https://github.com/Coderx-Gamer/shulker-dupe/blob/main/src/main/java/net/shulker/dupe/mixin/ShulkerBoxScreenMixin.java).

**Comment by N3rmis** [comment]
R u sure u have version 1.1.1 installed i believe i fixed it in that version

**Comment by Coderx-Gamer** [comment]
^^^
