### ISSUE TITLE
Wont dupe please help

### ISSUE THREAD

**Issue by ghost** [Coderx-Gamer/shulker-dupe#2]
Everything is there jsut it wont dupe idk if its ping but im on a friends relam on 1.17.1

**Comment by HoloPrism** [comment]
It might just be your ping or the server has PaperMC

**Comment by Darkking6275** [comment]
IS there a way to make it work with a server that has mc

**Comment by DamnUi** [comment]
??? dude it only works on a vanilla server must be 1.17 or above afaik and you must not have any other mods running

**Comment by Coderx-Gamer** [comment]
a few mods break this mod, i know that multiconnect breaks it I might fix it at some point but I don't have time probably
