### ISSUE TITLE
Is Anyone willing to create a Forge port?

### ISSUE THREAD

**Issue by Constantine415** [Coderx-Gamer/shulker-dupe#21]

**Comment by CCarbon1024** [comment]
yes,I make a forge version. Here https://github.com/CCarbon1024/shulker-dupe-forge

**Comment by Killerpickle8869** [comment]
How do you install it?
Can you make a video

**Comment by CCarbon1024** [comment]
@Killerpickle8869 What do you mean? The forge version or fabric version.

**Comment by lilithium-hydride** [comment]
> How do you install it? Can you make a video

There's nothing complicated warranting a video. Just drag the Forge or Fabric .jar (found in the project's Releases) into your mods folder like anything else.

**Comment by Coderx-Gamer** [comment]
I will not be making a forge port myself but you can use the mod above.
