### ISSUE TITLE
Its not letting me launch minecraft

### ISSUE THREAD

**Issue by Killerpickle8869** [Coderx-Gamer/shulker-dupe#23]
Whenever 'shulker-dupe_1.18.x_1.1.1.jar' is inside the mods folder Minecraft crashes with an error stating that Fabric isn't installed and any version of fabric is needed, but fabric is installed as it is the version that is being run.

**Comment by erxson** [comment]
install fabric api

**Comment by Killerpickle8869** [comment]
I have, it is the version/instance I was running minecraft but when I added the mod it either would cause minecraft to craft with the error above or the mod wouldn't load

**Comment by LawfulDmcBoo** [comment]
> 

You have to instal the 1.19 Fabric API, which can be downloaded on CurseForge. I too had this problem, and it was fixed my doing this.

**Comment by Coderx-Gamer** [comment]
Make sure you are downloading the right version of the mod (can be sub-release dependant) and your fabric version and fabric api need to be updated, some mods are incompatible with this so you will need to remove those.
