### ISSUE TITLE
Dupe only works for single-player but not for multiplayer

### ISSUE THREAD

**Issue by LouisChak** [Coderx-Gamer/shulker-dupe#24]
Title, I tried multiple 1.18 servers. Incase the server wasn't hosted on 1.18, I even tried activating a 1.18 server via a server host (the server is spigot 1.18). I then tried going into single player and it worked, is this dupe only for single-player and not for multiplayer?

**Comment by erxson** [comment]
Dupe doesn't work on spigot

**Comment by erxson** [comment]
Only vanilla and fabric servers

**Comment by Gapamata** [comment]
I recently tried it on 1.19 realms, and it worked. But it didn't work on 1.19.1

**Comment by Coderx-Gamer** [comment]
It does not work on paper or spigot and 1.19.1+.
