### ISSUE TITLE
when i press dupe the stuff in shulkerbox come back to me and shulker box break and nothing duped

### ISSUE THREAD

**Issue by armanwarrior** [Coderx-Gamer/shulker-dupe#27]

**Comment by erxson** [comment]
Dupe works only on vanilla servers (and fabric without fix mods)

**Comment by SlappMann** [comment]
Does it not work on spigot servers?

**Comment by Coderx-Gamer** [comment]
the dupe does not work on some modified servers such as paper or spigot.
