### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ItsBrogan** [Coderx-Gamer/shulker-dupe#3]
Would be nice to have a option to possibly disable the buttons from showing inside of the shulker so they aren't there all of the time

**Comment by Coderx-Gamer** [comment]
how do u want this to be implemented? with a command or something?

**Comment by Coderx-Gamer** [comment]
im updating the mod to 1.18 so ill add that when im updating it

**Comment by ItsBrogan** [comment]
I command or an option. Toggling it off would make it easier and mean you don't need to remove the mod or put it back whenever you want to show things just in case of people seeing. Thank you for the quick response as well!

**Comment by IDreaZyyy** [comment]
> im updating the mod to 1.18 so ill add that when im updating it

any eta on the release? All these servers updating to 1.18 without paper or spigot, this is so clutch brotha

**Comment by Coderx-Gamer** [comment]
Sorry about delaying this for like 9 months (xd) I forgot to implement it when updating to 1.18 and 1.19 I will add it to the current 1.19 release.
