### ISSUE TITLE
crashes in 1.19.1

### ISSUE THREAD

**Issue by zinba** [Coderx-Gamer/shulker-dupe#31]
shulker-dupe_1.19.x_1.2.0

fabric loader version 0.14.8
fabric-api-0.58.5+1.19.

[crash-2022-07-29_10.43.32-client.txt](https://github.com/Coderx-Gamer/shulker-dupe/files/9220927/crash-2022-07-29_10.43.32-client.txt)
1

**Comment by MasterGreenyMC** [comment]
I also had this problem. It seems to be no individual case.

**Comment by HimanshuSejwal** [comment]
i am also having this issue. will this be getting fix?

**Comment by Coderx-Gamer** [comment]
fixing this soon, side note I would not really recommend playing 1.19.1 lol

**Comment by Coderx-Gamer** [comment]
update: it does not actually work in 1.19.1+ it is not a problem with the mod rather the dupe has been fixed.
