### ISSUE TITLE
1.18?

### ISSUE THREAD

**Issue by DivineEssentia** [Coderx-Gamer/shulker-dupe#4]
ayo would u update this to 1.18 we would be very happy

**Comment by IDreaZyyy** [comment]
^

**Comment by JackDainzh** [comment]
Just edit the fabric_mod.json, easiest update of my life :)

**Comment by JackDainzh** [comment]
Or just use this: https://github.com/gingerchicken/shulker-dupe

**Comment by DivineEssentia** [comment]
> Or just use this: https://github.com/gingerchicken/shulker-dupe
thanks bro
