### ISSUE TITLE
Minecraft startup error

### ISSUE THREAD

**Issue by KrOik** [Coderx-Gamer/shulker-dupe#41]
Hello, I want to use this mod, but there are some problems during startup. I will attach an error report.
This is the fabric environment, version 1.19.2. Although I tried many times, the game still failed to start.
I'm sure this is not a mod conflict problem, because version isolation is enabled and only fabric, fabric API and shulker dupe are installed_ 1.19.x_ 1.2.1。
I hope I can get attention or solve it to help everyone. Thank you very much for your attention to this issue.
This is the issues from the translation software. I very much hope to communicate in English, but my ability is limited. Sorry.
[Error report - September 6, 2022.zip](https://github.com/Coderx-Gamer/shulker-dupe/files/9493238/Error.report.-.September.6.2022.zip)

**Comment by Coderx-Gamer** [comment]
Unfortunately this does *not* work on 1.19.1+, It is not a problem with the mod, Rather mojang has patched it.
