### ISSUE TITLE
my mc wont open

### ISSUE THREAD

**Issue by jaykay0972** [Coderx-Gamer/shulker-dupe#44]

**Comment by Coderx-Gamer** [comment]
Are you on 1.19.1 or above? Sadly mojang patched the dupe concept in 1.19.1 and in further versions.

**Comment by jaykay0972** [comment]
> Are you on 1.19.1 or above? Sadly mojang patched the dupe concept in 1.19.1 and in further versions.

yes i am i will lower my version now
