### ISSUE TITLE
my minecraft wont launch when i add another mod to my files even on 1.19

### ISSUE THREAD

**Issue by jaykay0972** [Coderx-Gamer/shulker-dupe#46]

**Comment by jaykay0972** [comment]
the mod is clientcommand

**Comment by MrBreakNFix** [comment]
UI utils is not compatable with every other mod

**Comment by Coderx-Gamer** [comment]
use 1.19 client commands it should work fine, you probably mixed up client commands 1.19.2/1 with 1.19

**Comment by jaykay0972** [comment]
Stfu
