### ISSUE TITLE
Minecraft 1.19.2 keeps crashing

### ISSUE THREAD

**Issue by fishybuisness1337** [Coderx-Gamer/shulker-dupe#47]
Fabric Profile 1.19.2 is installed
fabric-api-0.64.0+1.19.2
shulker-dupe_1.19.x_1.2.1 
these 2 mods only
[latest.log](https://github.com/Coderx-Gamer/shulker-dupe/files/9896395/latest.log)

**Comment by Kattoe101** [comment]
same

**Comment by 11011220** [comment]
same

**Comment by KotMilkMeoWtwo** [comment]
same

**Comment by Coderx-Gamer** [comment]
read
the
repository
description
