### ISSUE TITLE
Minecraft 1.19.2 won't launch

### ISSUE THREAD

**Issue by Arendale38** [Coderx-Gamer/shulker-dupe#48]
Fabric Profile 1.19.2 
fabric-api-0.66.0+1.19.2
shulker-dupe_1.19.x_1.2.1
only these 2 mods

**Comment by szdytom** [comment]
have you read the description of this repo?

>  A client-side fabric mod that makes it easier to perform the shulker dupe. (**discontinued for the time being as 1.19.1 has patched this, may look for bypasses soon**)
