### ISSUE TITLE
shulker-dupe-1.2.1 with fabric-api-0.58.5+1.19.1 results in a crash

### ISSUE THREAD

**Issue by egdod333** [Coderx-Gamer/shulker-dupe#49]
Compiled using Gradle 7.6
Attempted to run with fabric-loader-0.14.11-1.19.1
![image](https://user-images.githubusercontent.com/87278461/207935319-8b4069ff-3eb6-4579-b2fe-a4372070b8e3.png)
![image](https://user-images.githubusercontent.com/87278461/207935434-956cf686-703f-4266-9bc7-0fefcf539442.png)

**Comment by spsquared** [comment]
The dupe has been patched in 1.19.1, so there's really no point in using this mod with 1.19.1 anyways.
