### ISSUE TITLE
Will it work in Purpur1.19.3 if I join from 1.19

### ISSUE THREAD

**Issue by AbhigyanKr** [Coderx-Gamer/shulker-dupe#51]

**Comment by dbLuka22** [comment]
no they patched the dupe in 1.19.1

**Comment by dagarred** [comment]
and if the server has any plugin clinets like spigot the mod wont work

**Comment by Coderx-Gamer** [comment]
No, it doesn't work on anything spigot based or on versions above 1.19.0.
