### ISSUE TITLE
Notes say this is an official Mojang project while it is not.

### ISSUE THREAD

**Issue by Komos63** [Coderx-Gamer/shulker-dupe#57]
"Disclaimer: This is an official mojang project." should be changed to "Disclaimer: This is not an official Mojang project."

**Comment by Neodyminus** [comment]
This guy must be fun at parties...

**Comment by Coderx-Gamer** [comment]
bro i identify as a mojang employee so its an official mojang project

**Comment by MrBreakNFix** [comment]
same here i sexually identify as a monkey so thats why my pull request to remove the word "not" was accepted
