### ISSUE TITLE
I cannot get this addon to work

### ISSUE THREAD

**Issue by blamoyay** [Coderx-Gamer/shulker-dupe#9]
I've downloaded and unzipped this mod, but I cannot get it to work, I don't see the buttons and I've also tried keeping it zipped, and turning it into a .jar

**Comment by shadow01148** [comment]
What do you mean unzipped? The releases page already has a compiled .jar file.

**Comment by Coderx-Gamer** [comment]
You don't "unzip" the jar file, google how to install a fabric mod and it should work fine.
